### ISSUE TITLE
Support for creating a COPY of an existing graph

### ISSUE THREAD

**Issue by gkorland** [FalkorDB/FalkorDB#138]
Created by: @schwab
Source: https://github.com/RedisGraph/RedisGraph/issues/1076
To support some really large data import operations,we'd like to make a copy of some existing graph data bases and create partitions.  Is there any supported way to make a full copy of an existing graph key?  The closest thing we've found so far is the following lua script that should copy keys in redis, but it has type issues with graphs....

```
redis-graph:6379> eval "return redis.call('SET', KEYS[2], redis.call('GET', KEYS[1]))" 2 graph:ortho graph:ortho2
(error) ERR Error running script (call to f_1e76bbeee0b4759f31fcf5ac56b0a2f22ceec5b7): @user_script:1: WRONGTYPE Operation against a key holding the wrong kind of value 
```

**Comment by gkorland** [comment]
Origin comment by: @swilly22
Hi @schwab,
We'll try to introduce `GRAPH.CLONE` operation soon.

**Comment by gkorland** [comment]
Origin comment by: @schwab
Thank you. That would be awesome.

**Comment by gkorland** [comment]
Origin comment by: @swilly22
Hi @schwab,

Here's a pure Redis way to clone a graph key:
Assuming a graph name `imdb` is loaded,
below is a python script which will perform a cloning of it.

Basically the idea is to use Redis [`dump`](https://redis.io/commands/dump) command to get a binary representation of the key (RDB)
then we can use the [`restore`](https://redis.io/commands/restore) command to load the binary data to a key we specify.

```
import redis
r = redis.Redis(host='localhost', port=6379)

key = "imdb"
clone = "copy"

dump = r.dump(key)
r.restore(clone, 0, dump)
```

**Comment by gkorland** [comment]
Origin comment by: @jonaskello
I tried the approach suggested above using lua script:

```
eval "redis.call(\"RESTORE\", KEYS[2], 0, redis.call(\"DUMP\", KEYS[1]))" 2 mygraph mygraphcopy
```

This does copy the key but it also makes RedisGraph stop responding. After the above command any attempt to get any key from RedsGraph results in the error below:

```
>> GRAPH.QUERY mygraph "MATCH (a) RETURN a"
(error) RedisGraph module is currently replicating
```

I'm using a sinlge docker container locally on my computer with image `redislabs/redisgraph:2.4.1`. So no replication should be involved as far as I understand.

I also tried building my own image with Reids 6.2.1 to get the new  `COPY` command but that does not seem to work with RedisGraph:

```
>> copy mygraph mygraphcopy
(error) not supported for this module key
```

Is there some way to copy the graph?

**Comment by gkorland** [comment]
Origin comment by: @jonaskello
The DUMP/RESTORE approach works in image `redislabs/redisgraph:2.0.20` but image `redislabs/redisgraph:2.2.15` and above gives the `(error) RedisGraph module is currently replicating` error.

**Comment by gkorland** [comment]
Origin comment by: @swilly22
Hi @jonaskello, `DUMP` `RESTORE` would only work in you're restoring the graph under its original key name, this is a limitation introduced as part of supporting (replicating) large graphs,
as a suggestion on how to copy a graph please use:
1. DUMP original
2. `RENAME` original clone
3. RESTORE original 0 <DUMP_OUTPUT>

**Comment by gkorland** [comment]
Origin comment by: @jonaskello
@swilly22 Thanks, that will be very useful :-). I'll update #1626 with this suggestion and close it when I get it to work.

**Comment by swilly22** [comment]
use `GRAPH.COPY src dest` to copy graph `src` to `dest`
