### ISSUE TITLE
Stop using bulk mentions to spam people

### ISSUE THREAD

**Issue by jahed** [FalkorDB/FalkorDB#19]
I'm extremely disappointed that @gkorland and this project have decided to use GitHub's mentions feature to bulk spam hundreds of GitHub users. Despite knowing this and saying so in your email, you still decided to do so. GitHub has removed the discussion but of course the damage has already been done.

What exactly was this project's decision process when it decided to send such blatant spam to everyone's email and notifications inbox? Was it purely a misunderstand of what "[disruptive technology](https://github.com/FalkorDB/FalkorDB/blob/edc3456801fbb7ff85412b8f3202412caa00b5f8/README.md?plain=1#L4)" is? Or was it something more selfish? Let's have a moment of introspection and ensure this doesn't happen again.

**Comment by gkorland** [comment]
@jahed thanks for the feedback, I took it, it won't repeat.
