### ISSUE TITLE
Support for Redis COPY command

### ISSUE THREAD

**Issue by gkorland** [FalkorDB/FalkorDB#276]
Created by: @JoonasC
Source: https://github.com/RedisGraph/RedisGraph/issues/2366
At the moment AFAIK RedisGraph has no support for the Redis COPY command, which effectively makes it impossible to copy a graph. Could this be implemented?

**Comment by gkorland** [comment]
Origin comment by: @K-Jo
Though a valid request, can I ask why you would like to copy the graph @JoonasC?

**Comment by gkorland** [comment]
Origin comment by: @JoonasC
I have an application in which users can create projects, each project has a graph that is associated to it. The application also has/will have the functionality to copy/clone projects.

**Comment by gkorland** [comment]
Origin comment by: @LiorKogan
Related: https://github.com/RedisGraph/RedisGraph/issues/1076

**Comment by gkorland** [comment]
Origin comment by: @JoonasC
Any ETA on when this will be ready? I'm starting to really need this feature...

**Comment by swilly22** [comment]
Use `GRAPH.COPY src dest` to copy graph `src` to `dest`
