### ISSUE TITLE
[Feature] Bulk Loader?

### ISSUE THREAD

**Issue by DnOberon** [FalkorDB/FalkorDB#33]
Any plans on either utilizing or building a new bulk loader feature? That's the one thing that would stop us from moving across to FalkorDB anytime soon.

**Comment by gkorland** [comment]
What is not working with the existing bulk loader?

**Comment by DnOberon** [comment]
I didn’t even think to try it whoops. If that’s currently working and plans
are to continue to support it I’d consider this closed then :)

**Comment by gkorland** [comment]
Yes, it should work FalkorDB fully compatible with RedisGraph.
And we plan to release it under the Falkor name https://github.com/FalkorDB/falkordb-bulk-loader
