### ISSUE TITLE
Thinking about Vector Search

### ISSUE THREAD

**Issue by flowt-au** [FalkorDB/FalkorDB#35]
Just to add another possibility to FalkorDB...

I just watched this video:
[Workshop: Searching document data with Redis, JSON, and vector-similarity](https://www.youtube.com/watch?v=e4A_k-hFIa4)

The second half about Vector Search in Redis was, for me, the clearest explanation of how to use Redis for semantic searching on text (my main use-case). Maybe this is already possible with RedisGraph (except for the lack of support for Nested JSON). So, if FalkorDb could support using the graph nodes for Vector Search that would be fantastic. I guess if not, farming the relevant node text into a RedisJson store could also work? 

Anyway, just some thoughts.

Thanks,
Murray

**Comment by flowt-au** [comment]
Given I have next to zero knowledge of the internal workings of Redis Graph / FalkorDB / RedisJson, the following might be a terrible idea:
What if FalkorDB nodes were actually linked to a RedisJson key instead of storing on the nodes themselves? The nested Json and FT and VSS searching would then work via RedisJson. I can see that the Cypher pattern matching queries (still essential functionality) would need to somehow work with the fact that the data is "linked" rather than what I assume to be direct. 

Anyway, FWIW, just a thought to avoid FalkorDB having to reinvent the wheel in terms of nested Json and VSS.

Thanks again,
Murray

**Comment by swilly22** [comment]
Hi @flowt-au,
Support for vector indexing is right around the corner see [PR](https://github.com/FalkorDB/FalkorDB/pull/3)

**Comment by flowt-au** [comment]
Cool!! :-)
