### ISSUE TITLE
FalkorDBQAChain: unable to reproduce vlog results

### ISSUE THREAD

**Issue by schwab** [FalkorDB/FalkorDB#471]
I'm not sure if this is the best place to post this, but I was trying to follow Guy's blog post on Building a Q&A system
Using FalkorDB with LangChain step-by-step in ipynb with the LLM query.  I get the correct cypher result from the agent  but the full context does not have the text results (as the blog had, but instead it shows text about the graph nodes).

``` > Entering new FalkorDBQAChain chain...
Generated Cypher:
MATCH (p:Person)-[r:ACTED\_IN]->(m:Movie) WHERE p.name = 'Tom Cruise' AND m.title = 'Top Gun' RETURN p, m


```
Then an exception which ends like :
ResponseError: errMsg: Invalid input '\': expected '|', '*', '{', a parameter or ']' line: 1, column: 26, offset: 25 errCtx: MATCH (p:Person)-[r:ACTED\_IN]->(m:Movie) WHERE p.name = 'Tom Cruise' AND m.t

So apparently it's adding "\\" to the graph query which is breaking.

I'm running falkordb/falkordb:latest.

Here's the code dump (it's the same as the blog post)
```  
from langchain.chat_models import ChatOpenAI
from langchain.graphs import FalkorDBGraph
from langchain.chains import FalkorDBQAChain

graph = FalkorDBGraph(database="movies")

graph.query("""

   CREATE
       (al:Person {name: 'Al Pacino', birthDate: '1940-04-25'}),
       (robert:Person {name: 'Robert De Niro', birthDate: '1943-08-17'}),
       (tom:Person {name: 'Tom Cruise', birthDate: '1962-07-3'}),
       (val:Person {name: 'Val Kilmer', birthDate: '1959-12-31'}),
       (anthony:Person {name: 'Anthony Edwards', birthDate: '1962-7-19'}),
       (meg:Person {name: 'Meg Ryan', birthDate: '1961-11-19'}),

       (god1:Movie {title: 'The Godfather'}),
       (god2:Movie {title: 'The Godfather: Part II'}),
       (god3:Movie {title: 'The Godfather Coda: The Death of Michael Corleone'}),
       (top:Movie {title: 'Top Gun'}),

       (al)-[:ACTED_IN]->(god1),
       (al)-[:ACTED_IN]->(god2),
       (al)-[:ACTED_IN]->(god3),
       (robert)-[:ACTED_IN]->(god2),
       (tom)-[:ACTED_IN]->(top),
       (val)-[:ACTED_IN]->(top),
       (anthony)-[:ACTED_IN]->(top),
       (meg)-[:ACTED_IN]->(top)
""")

import os

os.environ['OPENAI_API_KEY']='API_KEY_HERE'
graph.refresh_schema()
model_name = os.getenv("MODEL_NAME")
chain = FalkorDBQAChain.from_llm( ChatOpenAI(model=model_name, temperature=0), graph=graph, verbose=True)

chain.run("Who played in Top Gun?")
```

**Comment by schwab** [comment]
OK, I fixed that issue by replacing "\\_" with "_" in the generated_cypher in FalkorDBQAChain, then I got an issue where the context was returning with values like:

```
Full Context:
[[<redis.commands.graph.node.Node object at 0x7f13f9d80ed0>, <redis.commands.graph.node.Node object at 0x7f13f9d81950>], [<redis.commands.graph.node.Node object at 0x7f13f9d81410>, 
```
Which I fixed by extracting the node's labels and properties into json.

```
context = self.graph.query(generated_cypher)[: self.top_k]
context = json.dumps([{y.label: y.properties} for x in context for y in x])
 ```
This fixed the problems for the default question (who played in Top Gun:

```
> Entering new FalkorDBQAChain chain...
Generated Cypher:
MATCH (p:Person)-[r:ACTED_IN]->(m:Movie) WHERE p.name = 'Tom Cruise' AND m.title = 'Top Gun' RETURN p, m
Full Context:
[{"Person": {"name": "Tom Cruise", "birthDate": "1962-07-3"}}, {"Movie": {"title": "Top Gun"}}, {"Person": {"name": "Tom Cruise", "birthDate": "1962-07-3"}}, {"Movie": {"title": "Top Gun"}}, {"Person": {"name": "Tom Cruise", "birthDate": "1962-07-3"}}, {"Movie": {"title": "Top Gun"}}, {"Person": {"name": "Tom Cruise", "birthDate": "1962-07-3"}}, {"Movie": {"title": "Top Gun"}}, {"Person": {"name": "Tom Cruise", "birthDate": "1962-07-3"}}, {"Movie": {"title": "Top Gun"}}, {"Person": {"name": "Tom Cruise", "birthDate": "1962-07-3"}}, {"Movie": {"title": "Top Gun"}}, {"Person": {"name": "Tom Cruise", "birthDate": "1962-07-3"}}, {"Movie": {"title": "Top Gun"}}]

> Finished chain.
'Tom Cruise played in Top Gun.'

````
But other questions are still struggling.  For instance : 
chain.run("What movies are in the data?")
Tries to use in valid cypher:

> Entering new FalkorDBQAChain chain...
Generated Cypher:
MATCH (p:Person)-[r:ACTED_IN]->(m:Movie) WHERE p.keys(['name', 'birthDate']) RETURN m.title as movie

ResponseError: Unknown function 'p.keys'

**Comment by schwab** [comment]
You're correct Roi, the differences are coming from the language model. I didn't realize how much it was relying on the language model to generate the correct cypher queries.  I'm using vicuna-7B-16K (and other variants on FastChat Api).  It's possible to get better results with some prompt tweaking and other tricks, but it looks like I'll need a variant per model to use offline or different LLMs.

**Comment by swilly22** [comment]
Indeed there's no guarantees if an LLM model will manage to produce valid Cypher queries, this is one of the more delicate areas in this type of systems.

I would love to hear about your progress with this project.

**Comment by schwab** [comment]
Closing this as the solution is llm dependent.  I may put in a pull request with a vicuna version of the prompt of I can get it all working reliably.  The good news it that is possible to coax the vicuna model into giving consistently answers through an interactive chat so it should be possibly to create a one shot prompt that will do the same thing.  Sometimes you just have to know the model will enough that you can talk it's language so to 🗣️
