### ISSUE TITLE
Different results when counting * and c

### ISSUE THREAD

**Issue by gkorland** [FalkorDB/FalkorDB#487]
ref: https://github.com/RedisGraph/RedisGraph/issues/3214

I execute two queries on my empty RedisGraph and get an error.

Redis version:7.2.0
RedisGraph version: v2.12.10
operating system: windows 11
API：Cypher version 9

To reproduce:
```
OPTIONAL MATCH (c)-[:PP]-() WHERE c IS NOT NULL RETURN count(*)
OPTIONAL MATCH (c)-[:PP]-() WHERE c IS NOT NULL RETURN count(c)
```

Actual behavior:
When counting by *,the result is 1 but when counting by c the result becomes 0.
I'm asking if this is an expected result or a bug?

**Comment by gkorland** [comment]
@ljhhuxiaoba

**Comment by ljhhuxiaoba** [comment]
Thanks for you explanation!
