### ISSUE TITLE
Recommended Upgrade Path for existing Redis_Graph services.

### ISSUE THREAD

**Issue by schwab** [FalkorDB/FalkorDB#547]
In our environment we have a number of servers that are being used to service production users that are using Redis Graph which is currently on Redis Server 6.2.7.  However we'd like to upgrade these to FalkorDb:v4.0.3 which is using Redis Server:7.2.3.  Typically we'd just upgrade the docker image and it would pickup the existing rdb file and start up with existing data, however when we try to do this, we are getting RDB Format errors and :
Fatal error loading the DB: Invalid argument. Exiting.

What is the recommended way to upgrade to FalkorDb and maintain the existing data?

**Comment by schwab** [comment]
I suppose if there is no direct way to load from the RDB file, the next question would be how can we extract and reload the data from a graph in a way that would allow it to be reloaded in another graph?  I was thinking maybe something that did the opposite of the bulk importer does that could dump everything to csv or some other format.

**Comment by AviAvni** [comment]
I was able to load rdb from RedisGraph to FalkorDB which version of RedisGraph you use? can you share more details?

**Comment by schwab** [comment]
I'm closing the issue because it turns out we had mixed our rdb files with redis dump files.  With the dump files it works correctly and no issues restoring the graph into falkordb.
