### ISSUE TITLE
How to visualize the graph created?

### ISSUE THREAD

**Issue by plaban1981** [FalkorDB/FalkorDB#549]
Generaally after creating the graphstore if we want to visualize the graph what is the code or the package to do so ?. Please advice

The following option is availeable in llamindex

## create graph
from pyvis.network import Network

g = index.get_networkx_graph()
net = Network(notebook=True, cdn_resources="in_line", directed=True)
net.from_nx(g)
net.show("falkordbgraph_draw.html")

**Comment by gkorland** [comment]
Thanks for pointing it. We're working on a stand alone graphical user interface for FalkorDB.
See: https://github.com/FalkorDB/falkordb-browser

**Comment by gkorland** [comment]
ref #559
