### ISSUE TITLE
A question about the docker image size

### ISSUE THREAD

**Issue by flowt-au** [FalkorDB/FalkorDB#554]
I am moving across from RedisGraph to FalkorDB, and thank you for continuing the work! :-)

I might be misunderstanding something basic here but I notice the following difference in image sizes between redis-stack-server 6.2.6-v10 at 357Mb and Falkor:latest (4.0.3) at 3286Mb. 

Is it really so much bigger? That seems strange. I can't see a smaller image in DockerHub.

I am not complaining, I am simply not understanding what accounts for the size difference. Is it the vector indexing additions?

Thanks,
Murray

**Comment by gkorland** [comment]
@flowt-au you're right, the docker we published is based on vanilla Ubuntu, we're working on reducing its size.

**Comment by flowt-au** [comment]
Cool. I was hoping to sandbox multiple FalkorDB instances to specific Quarkus app containers. Not a deal breaker but smaller would be great! Thanks. :-)

**Comment by swilly22** [comment]
Hi @flowt-au,
We've just released our `4.0.4` version, we've been able to reduce our overall docker image size to ~100MB (compressed).

**Comment by flowt-au** [comment]
That's great news! Thank you. Looking forward to trying it out. :-)
