### ISSUE TITLE
Support for Redis COPY command 

### ISSUE THREAD

**Issue by gkorland** [FalkorDB/FalkorDB#58]
ref: https://github.com/RedisGraph/RedisGraph/issues/2366
ref: https://github.com/orgs/FalkorDB/discussions/54#discussioncomment-7080942
@JoonasC

**Comment by JoonasC** [comment]
Any progress on this @gkorland ?

**Comment by swilly22** [comment]
The only valid option I see at the moment would be to use redis `DUMP` and `RESTORE` commands:

Here's a quick python example:
```python
import redis
conn = redis.Redis()

# Dump key 'railroad' into memory
dump = conn.dump('railroad')

# Restore 'railroad' key into a new key 'copy-of-railroad'
conn.restore(name='copy-of-railroad', ttl=0, value=dump)
```

**Comment by swilly22** [comment]
Hi, sorry, at the moment we don't have a sufficient solution for making copied of a graph

**Comment by JoonasC** [comment]
@swilly22 Ok, is there a cause for this? Is it because FalkorDB is no longer part of Redis?

**Comment by JoonasC** [comment]
@swilly22 Does the DUMP/RESTORE trick still work?

**Comment by JoonasC** [comment]
@swilly22 @gkorland Hey, any updates?

**Comment by gkorland** [comment]
@swilly22 just started to work on this task

**Comment by JoonasC** [comment]
Ok, great to hear

**Comment by swilly22** [comment]
@JoonasC you can use `GRAPH.COPY src dest` to clone `src` graph to `dest`.
