### ISSUE TITLE
DB Browser only listening on 127.0.0.1

### ISSUE THREAD

**Issue by chlsmith** [FalkorDB/FalkorDB#599]
I'm trying to run the FalkorDB container with both the db and the browser exposed to the network.   The browser shows that it's running on 127.0.0.1:3000, but I believe it needs to be on 0.0.0.0:3000 so I can connect to the port remotely.

How can I configure it to run this way?  I see the BROWSER flag is set to 1 and it does respond locally within the container, but I cannot connect to it from anywhere else on port 3000.

**Comment by dudizimber** [comment]
@chlsmith How are you running the container?
Can you try the following command, please?
`docker run -p 6379:6379 3000:3000 falkordb/falkordb`
