### ISSUE TITLE
Duplicated label when creating and deleting unrelated node

### ISSUE THREAD

**Issue by DominicWuest** [FalkorDB/FalkorDB#628]
I found a discrepancy when running two semantically equivalent queries against an empty database:

---
1:
```cypher
CREATE (y:B:C) RETURN y
```

Returns a node with label `:B:C`.

---
2:
```cypher
CREATE (x:A) DELETE x
CREATE (y:B:C) RETURN y
```

Returns a node with label `:C:C`.

---

I believe the queries mentioned above are semantically equivalent and thus their result should be the same.

Additionally, this result only occurs after the commit **deedfef**, before which both queries return the same result.

I encountered this issue when testing queries on the **FalkorDB master branch** in a Docker container running **redis:7.2.3-bookworm**.

### Steps to reproduce
Run the aforementioned, semantically equivalent, queries against an empty database and observe that their results differ.

### Expected behavior
The queries should result in the same behavior

### Actual behavior
The query results differ

**Comment by swilly22** [comment]
Hi @DominicWuest,
Thank you for reporting!

Testing this query against FalkorDB version `4.0.7`

```sh
docker run -p 6379:6379 -it --rm falkordb/falkordb:latest
```

```
127.0.0.1:6379> FLUSHALL
OK
127.0.0.1:6379> GRAPH.QUERY g "CREATE (x:A) DELETE x CREATE (y:B:C) RETURN y"
1) 1) "y"
2) 1) 1) 1) 1) "id"
            2) (integer) 0
         2) 1) "labels"
            2) 1) "B"
               2) "C"
         3) 1) "properties"
            2) (empty array)
3) 1) "Labels added: 3"
   2) "Nodes created: 2"
   3) "Nodes deleted: 1"
   4) "Cached execution: 0"
   5) "Query internal execution time: 0.548916 milliseconds"
```

Can you please confirm from your end?

**Comment by DominicWuest** [comment]
Thanks for looking into this @swilly22!

That is interesting, when using redis-cli (or the Python client), I see the same behaviour. This might be an issue with the Go client then, I might look into it further later on :)
