### ISSUE TITLE
Running a query causes the Docker container to exit abnormally

### ISSUE THREAD

**Issue by gkorland** [FalkorDB/FalkorDB#63]
This issue was imported from the original issue: https://github.com/RedisGraph/RedisGraph/issues/3191
Created by: @ljhhuxiaoba

I execute a query on my empty RedisGraph and get an error.

Redis version:7.2.0
RedisGraph version: v2.12.9
operating system: windows 10
API：Cypher version 9
query:UNWIND NULL AS a0 WITH a0 ORDER BY NULL DESC WHERE false REMOVE (NULL).k RETURN *
error message:"Reached the max retries per request limit (which is 1). Refer to "maxRetriesPerRequest" option for details."

Actual behavior:
The query failed and the redisgraph container exited abnormally with the error message.

**Comment by gkorland** [comment]
This issue was imported from the original issue: https://github.com/RedisGraph/RedisGraph/issues/3191
Created by: @ljhhuxiaoba

**Comment by AviAvni** [comment]
fixed
