### ISSUE TITLE
Property disappears when creating and deleting unrelated node

### ISSUE THREAD

**Issue by DominicWuest** [FalkorDB/FalkorDB#630]
I found a discrepancy when running two semantically equivalent queries against an empty database:

---
1:
```cypher
CREATE (y{N:0, M:0}) RETURN y
```
Produces:
```
+-----------+
|     y     |
+-----------+
| {M:0,N:0} |
+-----------+
```

---
2:
```cypher
CREATE (x{n0:0}) DELETE x
CREATE (y{N:0, M:0}) RETURN y
```
Produces:
```
+-------+
|   y   |
+-------+
| {M:0} |
+-------+
```
---

I believe the queries mentioned above are semantically equivalent and thus their result should be the same.

This bug has been present since at least `RedisGraph v1.99.8`. 

I encountered this issue when testing queries on the **FalkorDB master branch** in a Docker container running **redis:7.2.3-bookworm**.

### Steps to reproduce
Run the aforementioned, semantically equivalent, queries against an empty database and observe that their results differ.

### Expected behavior
The queries should result in the same behavior

### Actual behavior
The query results differ

**Comment by swilly22** [comment]
Hi @DominicWuest 

This is what I'm getting on both my local machine running the edge version of FalkorDB and on FalkorDB version 4.0.7

```sh
docker run -p 6379:6379 -it --rm falkordb/falkordb:latest
```

```
127.0.0.1:6379> graph.query g "CREATE (x{n0:0}) DELETE x CREATE (y{N:0, M:0}) RETURN y"
1) 1) "y"
2) 1) 1) 1) 1) "id"
            2) (integer) 0
         2) 1) "labels"
            2) (empty array)
         3) 1) "properties"
            2) 1) 1) "N"
                  2) (integer) 0
               2) 1) "M"
                  2) (integer) 0
3) 1) "Nodes created: 2"
   2) "Properties set: 3"
   3) "Nodes deleted: 1"
   4) "Cached execution: 0"
   5) "Query internal execution time: 0.343542 milliseconds"
```
