### ISSUE TITLE
How to check if one index is already existing when we create a index.

### ISSUE THREAD

**Issue by noahxzhu** [FalkorDB/FalkorDB#661]
The question like the title mentioned, when I run "CREATE INDEX FOR (n:`Entity`) on (n.id)" to create an index, I will get an error once the index already exists.

Or is there convenient way like create index in postgresql "CREATE INDEX IF NOT EXISTS" to create a index in FalkorDB？

**Comment by swilly22** [comment]
You can use the following query to check if an index already exists:
```cypher
GRAPH.QUERY my_graph "CYPHER lbl='Entity' prop='id'
CALL db.indexes() YIELD label, properties
WHERE label = $lbl AND $prop in properties
RETURN 1 as index_exists"
```
