### ISSUE TITLE
Malformed query error when alias starts with a number

### ISSUE THREAD

**Issue by JakkoJokiranta** [FalkorDB/FalkorDB#689]
Hi there,

Running latest `falkordb/falkordb:edge` image (`9a52710dee90`),
I've found that FalkorDB complains when an alias starts by a number instead of an alpha-char

`CREATE (acbad71:Node {whatever: 'yes'}) --compact` -> OK
`CREATE (2cbad71:Node {whatever: 'yes'}) --compact` -> Invalid input '2': expected an identifier, a label, ...`

**Comment by gkorland** [comment]
The problem with the query is that it attempts to use a numeric value (2acbad71) as a label for the node, which is not allowed. In Cypher, labels must be alphanumeric strings that start with a letter.
