### ISSUE TITLE
Parameter-dependent query results should not be cached

### ISSUE THREAD

**Issue by Empty-Glasss** [FalkorDB/FalkorDB#713]
Version: FalkorDB v4.0.10

How to reproduce (starting with an empty graph):

`GRAPH.QUERY g "CYPHER param=1 WITH 4 AS X WHERE $param = 1 RETURN X"`
`GRAPH.QUERY g "CYPHER param=2 WITH 4 AS X WHERE $param = 1 RETURN X"`

This last query returns the node, even though it shouldn't. It seems this is a bug with the query planner caching, because executing the last query again with some small changes (e.g. an extra whitespace) will make it return the correct result.

Thanks in advance.

**Comment by swilly22** [comment]
Thank you @Empty-Glasss for reporting, this is indeed a bug in the optimization / caching logic.
A PR with a fix is available
