### ISSUE TITLE
Similairty algorithms

### ISSUE THREAD

**Issue by gkorland** [FalkorDB/FalkorDB#74]
Created by: @sachaarbonel
Source: https://github.com/RedisGraph/RedisGraph/issues/326
Hi Redis Team,

do you have any plans to implement similarity algorithms in near future? Like cosine similarity for example in order to use redisgraph as a recommendation engine.

Reference: https://neo4j.com/docs/graph-algorithms/current/algorithms/similarity-cosine/

**Comment by gkorland** [comment]
Origin comment by: @K-Jo
Hi @Sach97 

We have some more graph algorithms on our roadmap, however it looks like you are more looking for a function that would take in two vectors and return a similarity, essentially wrapping sqrt, pow and sum functions.  We will add this to our roadmap, but it will most likely be the second half of this year.  Will keep you posted here!

**Comment by gkorland** [comment]
Origin comment by: @Raidus
Any updates on this? :-)

**Comment by YoanSallami** [comment]
Hello ! Any update on this ? in the vector demo we can only use the euclidean distance, and for many similarity search cosine is better.. :)

**Comment by AviAvni** [comment]
Now you can use cosine
