### ISSUE TITLE
FalkorDB violates the relation uniqueness requirements of Cypher standard

### ISSUE THREAD

**Issue by Aurora-yzj** [FalkorDB/FalkorDB#740]
FalkorDB seems to violate the uniqueness requirements when matching relations, as specified in the openCypher standard, chapter "Pattern-Uniqueness"(https://s3.amazonaws.com/artifacts.opencypher.org/openCypher9.pdf):
![image](https://github.com/user-attachments/assets/c535f2b9-899f-4dba-88e0-a5a74e2d092c)

For example, suppose we build a database using the following queries:
```cypher
CREATE (n0{id : 2});
CREATE (n0{id : 5});
MATCH (n0 {id : 5}), (n1 {id : 2}) MERGE(n0)-[r :T1 {id : 24}]->(n1);
```
And then run the Cypher query:
```cypher
MATCH (n0)-[r0]-(n1)-[r1]-(n2) WHERE true RETURN n0.id, r0.id, n1.id, r1.id, n2.id
```
There should be no result, as such a pattern does not exist if we do not count repetitive relations (assigning relation 24 to both r0 and r1), and other Cypher-based databases indeed follow this rule, for example Memgraph and neo4j:

![image-1](https://github.com/user-attachments/assets/e83b29c4-c6f5-49f5-82ff-7b5b4307e775)

However, FalkorDB violates this property and give the result:
![image-2](https://github.com/user-attachments/assets/900bb26f-1bee-40e1-af1c-9ae89dcfe366)

Such inconsistency with the standard could cause trouble when programming with FalkorDB. Fix would be very appreciated. Thank you!

**Comment by dorukkarinca** [comment]
#694 ?

**Comment by Aurora-yzj** [comment]
> #694 ?

Thank you! I'll add edge tracking manually.
