### ISSUE TITLE
Case insensitive WHERE filters

### ISSUE THREAD

**Issue by schwab** [FalkorDB/FalkorDB#754]
Is it possible to perform case-insensitive filters for instance on the WHERE clause?  Currently matching  statement like :
```
MATCH (x) WHERE x.property = "BOB"
```
Will not find nodes like:
```
(x:Person {property:"bob"}) 
```
Is there anyway to get this work?

**Comment by AviAvni** [comment]
you can use toLower function
MATCH (x) WHERE toLower(x.property) = "bob"

you can also utilize full-text index see https://docs.falkordb.com/cypher/index

**Comment by schwab** [comment]
Thank you Avi.
