### ISSUE TITLE
Relationships vector indexing not working

### ISSUE THREAD

**Issue by YoanSallami** [FalkorDB/FalkorDB#789]
Hello, I use the following indexing query: "CREATE VECTOR INDEX FOR ()-[r:FACT]->() ON (r.vector) OPTIONS {dimension:$dim, similarityFunction:$distance}"

With dim being 384 and distance "cosine" or "enclidean" and I always get no results, the graph is correctly populated.

Then the following query to get the results:

'CALL db.idx.vector.queryRelationships("FACT", "vector", $k, vecf32($vector)) YIELD relationship, score RETURN relationship._id_ AS id, score'

Here is the code used to populate the graph:

```
params = {
    "id": fact_id,
    "subject_id": str(fact.subj.id),
    "object_id": str(fact.obj.id),
    "relationship": fact.rel.name,
    "vector": list(fact.vector) if fact.vector is not None else None,
    "metadata": json.dumps(fact.metadata),
}
self._graph.query(
    " ".join([
        "MATCH (s:Entity {id: $subject_id}),",
        "(o:Entity {id: $object_id})",
        "MERGE (s)-[r:FACT {_id_: $id}]->(o)",
        "SET",
        "r.relation=$relationship,",
        "r.vector=$vector,",
        "r.metadata=$metadata",
    ]),
    params=params,
)
```

**Comment by AviAvni** [comment]
Try
```
params = {
    "id": fact_id,
    "subject_id": str(fact.subj.id),
    "object_id": str(fact.obj.id),
    "relationship": fact.rel.name,
    "vector": list(fact.vector) if fact.vector is not None else None,
    "metadata": json.dumps(fact.metadata),
}
self._graph.query(
    " ".join([
        "MATCH (s:Entity {id: $subject_id}),",
        "(o:Entity {id: $object_id})",
        "MERGE (s)-[r:FACT {_id_: $id}]->(o)",
        "SET",
        "r.relation=$relationship,",
        "r.vector=vecf32($vector) ,",
        "r.metadata=$metadata",
    ]),
    params=params,
)
```

**Comment by AviAvni** [comment]
the diff between
```CREATE (:N { vec: [1, 2, 3] })```
to
```CREATE (:N { vec: vecf32([1, 2, 3]) })```
is that in the first query the vec attribute store array that don't indexed in the vector index and in the second query it store a vector that stored in the vector index

**Comment by YoanSallami** [comment]
You are right, thank you very much! I got the correct one for my nodes retrievals, my bad !
