### ISSUE TITLE
Question: Migration from neo4j to FalkorDB

### ISSUE THREAD

**Issue by nickknyc** [FalkorDB/FalkorDB#790]
Maybe I am missing something, but I would expect there would be a clear path to move from neo4j to falkordb. Frankly, I haven't found any info on migrating or even importing from anything other than Redisgraph. 

I would really appreciate any specific instructions - I would be using the apoc.export from neo4j and can go to either graphml or csv. If another format is preferred please let me know. If there are any special things I should include or exclude, please let me know. 

If the bulk upload functionality is what I should be using, please let me know. i was under the impression this was for redis folks. https://github.com/falkordb/falkordb-bulk-loader

thanks

**Comment by nickknyc** [comment]
@AviAvni - I ran into problems using the stock apoc export functions in neo4j. What I ended up with are the attached python scripts which have cypher queries in them. They worked really well. 
[import_graph.zip](https://github.com/user-attachments/files/17062858/import_graph.zip)

**Comment by AviAvni** [comment]
Great so can it be closed?
Also if you want you can write a blog with your code

**Comment by nickknyc** [comment]
thanks for getting me on the right track!
