### ISSUE TITLE
does node label support chinese?

### ISSUE THREAD

**Issue by qiankunli** [FalkorDB/FalkorDB#818]
when I run 
```
MERGE (e:`__Entity__` {id: '刘备'})
SET e += {age:16}
SET e.name = '刘备'
WITH e
SET e:人物
```
or 
```
MERGE (e:`__Entity__` {id: '刘备'})
SET e += {age:16}
SET e.name = '刘备'
WITH e
SET e:'人物'
```

<img width="343" alt="image" src="https://github.com/user-attachments/assets/2fc68f8a-6ba0-4909-af1e-565f6a5a6a81">

does node label support chinese?

**Comment by qiankunli** [comment]
> I don't believe so, labels, relationship types and attribute names are all ASCII

Is there any consideration for supporting Unicode in the future?

**Comment by swilly22** [comment]
At the parser level, I'm not sure.
