### ISSUE TITLE
Assessing SSPL Open-Source Requirements Using FalkorDB

### ISSUE THREAD

**Issue by howardshaw** [FalkorDB/FalkorDB#819]
We plan to build an internal Q&A system using a knowledge graph based on FalkorDB. 
To integrate with standalone knowledge graph extraction algorithm via API, we’ll need to expose FalkorDB’s interface for adding entities and triples. 
This interface won’t be accessible to regular users, and the service is strictly for internal use.

Given these factors, would we be required to open-source our code under SSPL?

**Comment by gkorland** [comment]
@howardshaw  Technically if your product doesn't offer FalkoprDB functionality as a service to your users you can use it without the need to open source your product.
If your product is a Q&A system and not a DBaaS you should be fine.
