### ISSUE TITLE
how to override node properties?

### ISSUE THREAD

**Issue by qiankunli** [FalkorDB/FalkorDB#821]
I want to delete all properties of a node (except for the id) and assign new properties to it.

I tried using the following Cypher query:
```
MATCH (n {id: $id})
WITH n, [prop IN keys(n) WHERE prop <> 'id'] AS props
UNWIND props AS prop
REMOVE n.prop
SET n += $properties
SET n.name = $name 
```

Where name is '诸葛亮3' and properties is {'age': 21, 'b_5a6Y6IGM': '丞相5'}.

However, I found that the old properties were not removed. Could you provide some suggestions?

**Comment by swilly22** [comment]
```cypher
MATCH (n {id: $id})
SET n = $properties
```

This will overwrite `n` attribute-set with the new map `$properties`
To retain the node's original `id` make sure it is part of `$properties`

e.g.

```cypher
MATCH (n {id: 4})
SET n = {id: 4, score: 6}
```cypher

See [docs](https://docs.falkordb.com/cypher/set.html)

**Comment by qiankunli** [comment]
assume the original  node(n) had 3 attributes: `{'a': a, 'b': b, 'c': c}`. Now I want to overwrite it with `{'a': a1, 'd': d}`. 

```
MATCH (n {id: $id})
SET n += {'a': a1, 'd': d, id:xx, name: xx}
```
The issue is that attributes b and c have not been deleted.

Strangely, when I execute the cypher dsl  in the web UI,it works fine, but when I execute it by the FalkorDB Python SDK, there are issues. @swilly22

**Comment by qiankunli** [comment]
sorry, I've discovered that the real issue might be with the web UI.

**Comment by swilly22** [comment]
Please feel free to open an issue at: https://github.com/FalkorDB/falkordb-browser
