### ISSUE TITLE
FalkorDB Crash - RSSortingVector_Put

### ISSUE THREAD

**Issue by schwab** [FalkorDB/FalkorDB#822]
This morning, one of our falkordb servers started crashing with the following partial logs:

=== REDIS BUG REPORT START: Cut & paste starting from here ===
11:M 05 Nov 2024 17:54:24.228 # Redis 7.2.4 crashed by signal: 11, si_code: 1
11:M 05 Nov 2024 17:54:24.228 # Accessing address: 0x1
11:M 05 Nov 2024 17:54:24.228 # Crashed running the instruction at: 0x7be0fe4eadc2

------ STACK TRACE ------
EIP:
/FalkorDB/bin/src/falkordb.so(RSSortingVector_Put+0x22)[0x7be0fe4eadc2]

Backtrace:
/lib/x86_64-linux-gnu/libc.so.6(+0x3c050)[0x7be0ff4f4050]
/FalkorDB/bin/src/falkordb.so(RSSortingVector_Put+0x22)[0x7be0fe4eadc2]
/FalkorDB/bin/src/falkordb.so(+0x1da047a)[0x7be0fe55647a]
/FalkorDB/bin/src/falkordb.so(Document_AddToIndexes+0xac)[0x7be0fe55785c]
/FalkorDB/bin/src/falkordb.so(RediSearch_IndexAddDocument+0xf6)[0x7be0fe4e4bf6]
/FalkorDB/bin/src/falkordb.so(Index_IndexNode+0x73)[0x7be0fca88793]
/FalkorDB/bin/src/falkordb.so(RdbLoadNodes_v14+0x260)[0x7be0fca9aa60]
/FalkorDB/bin/src/falkordb.so(RdbLoadGraphContext_latest+0x307)[0x7be0fca9a0f7]
/FalkorDB/bin/src/falkordb.so(RdbLoadGraph+0x3f)[0x7be0fca9b59f]
/FalkorDB/bin/src/falkordb.so(+0x2ee5f5)[0x7be0fcaa45f5]
redis-server *:6379(rdbLoadObject+0x62a)[0x64dc34e5465a]
redis-server *:6379(rdbLoadRioWithLoadingCtx+0x71e)[0x64dc34e579be]
redis-server *:6379(rdbLoad+0xfc)[0x64dc34e585cc]
redis-server *:6379(loadDataFromDisk+0xa3)[0x64dc34e1c9a3]
redis-server *:6379(main+0x2d2)[0x64dc34df5562]
/lib/x86_64-linux-gnu/libc.so.6(+0x2724a)[0x7be0ff4df24a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85)[0x7be0ff4df305]
redis-server *:6379(_start+0x21)[0x64dc34df5e41]

------ REGISTERS ------
11:M 05 Nov 2024 17:54:24.233 # 
RAX:0000000000000004 RBX:0000000000000001
RCX:0000000000000001 RDX:00007be07d63aa00
RDI:0000000000000000 RSI:0000000000000000
RBP:0000000000000000 RSP:00007ffdcc8083f0
R8 :0000000000000000 R9 :00007be0ff050348
R10:00007be0ff000478 R11:00007be0ff000470
R12:0000000000000000 R13:00007be0ff0502a0
R14:00007be07eb35c80 R15:00000000000001f8
RIP:00007be0fe4eadc2 EFL:0000000000010206
CSGSFS:002b000000000033
11:M 05 Nov 2024 17:54:24.233 # (00007ffdcc8083ff) -> 00007be0fe55785c
11:M 05 Nov 2024 17:54:24.233 # (00007ffdcc8083fe) -> 00007be07eb35c80
11:M 05 Nov 2024 17:54:24.233 # (00007ffdcc8083fd) -> 00007be07d63a5f8
11:M 05 Nov 2024 17:54:24.233 # (00007ffdcc8083fc) -> 00007be07d63a9f8
11:M 05 Nov 2024 17:54:24.233 # (00007ffdcc8083fb) -> 00007be0ff0502a0
11:M 05 Nov 2024 17:54:24.233 # (00007ffdcc8083fa) -> 0000000000000001
11:M 05 Nov 2024 17:54:24.233 # (00007ffdcc8083f9) -> 561900903d996f00
11:M 05 Nov 2024 17:54:24.233 # (00007ffdcc8083f8) -> 00000000000001c0
11:M 05 Nov 2024 17:54:24.233 # (00007ffdcc8083f7) -> 00007be0fe55647a
11:M 05 Nov 2024 17:54:24.233 # (00007ffdcc8083f6) -> 00007be0ff0502a0
11:M 05 Nov 2024 17:54:24.233 # (00007ffdcc8083f5) -> 0000000000000000
11:M 05 Nov 2024 17:54:24.233 # (00007ffdcc8083f4) -> 00007be07d63a9f8
11:M 05 Nov 2024 17:54:24.233 # (00007ffdcc8083f3) -> 00007be07d63a5f8
11:M 05 Nov 2024 17:54:24.233 # (00007ffdcc8083f2) -> 00007be07e01da40
11:M 05 Nov 2024 17:54:24.233 # (00007ffdcc8083f1) -> 561900903d996f00
11:M 05 Nov 2024 17:54:24.233 # (00007ffdcc8083f0) -> 00007be081ec1e8c

------ INFO OUTPUT ------
# Server
redis_version:7.2.4
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:a1619e5314b0932f
redis_mode:standalone
os:Linux 6.9.3-76060903-generic x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
****
...

------ DUMPING CODE AROUND EIP ------
Symbol: RSSortingVector_Put (base: 0x7be0fe4eada0)
Module: /FalkorDB/bin/src/falkordb.so (base 0x7be0fc7b6000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=0x7be0fe4eada0 -D -b binary -m i386:x86-64 /tmp/dump.bin
------
11:M 05 Nov 2024 17:54:31.994 # dump of function (hexdump of 162 bytes):
f30f1efa81fe000400000f8f80000000415541544989fc554863ee5389cb4883ec18488b7cef014885ff743b8b470ca900ffff7f742889c125ff000080c1e90881c1ffff7f0081e1ffff7f0089cec1e60809f089470c85c90f84b200000049c744ec010000000083fb03746483fb05744783fb017422488b054b3f6500498944ec014883c4185b5d415c415dc30f1f00c30f1f8000000000f20f1002e81f73010049
Function at 0x7be0fe502160 is RS_NumVal

This machine is running falkordb/falkordb:v4.0.6. This happened about 10 seconds after a successful data import, so it's unclear exactly what caused the condition. We have reproduced it by copying the rdb to another machine running the same version of the graph.

**Comment by AviAvni** [comment]
Since 4.0.6 we update the vector index code with a lot of bug fixes it will be good if you upgrade to latest version

**Comment by schwab** [comment]
Confirmed, I was able to get the failing RDB up and running by switching to falkordb:latest.  It did take over an hour to startup the first time though. During that time it was using ~10cores at 100%. When that completed it settled down and the graph works fine now.

**Comment by swilly22** [comment]
@schwab 
Regarding the slow load time.

Is it possible that your graph contains "multi-edge" i.e. two or more edges of the same relationship type connecting the same set of source and dest nodes?

For example:
```cypher
CREATE (src)-[:R]->(dest), (src)-[:R]->(dest)
```

If you do have "multi-edges" in your graph then the next upcoming release of FalkorDB will improve loading time dramatically.

If not, then my guess most of the loading time revolve around vector indexing. this can be speed up using a CPU ARCH which supports AVX operations e.g. Intel CPUs.

**Comment by schwab** [comment]
Yeah, there are some multi-edge graphs. This seemed to be OK with 4.0.6. but with 4.3 it's causing very long load times. I'm trying to test everything before upgrading to 4.3.
