### ISSUE TITLE
Unrelated `FOREACH` causes `UNWIND` to be run in reverse

### ISSUE THREAD

**Issue by CelineWuest** [FalkorDB/FalkorDB#832]
I found a discrepancy when running two semantically equivalent queries against an empty database:

---
1:
```cypher
UNWIND [0, 1] AS x

MERGE ()
CREATE ({n1:x})
---
MATCH (n)
RETURN n
```
Produces:
```
+--------+
|   n    |
+--------+
| {}     |
| {n1:1} |
+--------+
```

---
2:
```cypher
UNWIND [0, 1] AS x
FOREACH (n0 IN [] | CREATE () )
MERGE ()
CREATE ({n1:x})
---
MATCH (n)
RETURN n
```
Produces:
```
+--------+
|   n    |
+--------+
| {}     |
| {n1:0} |
+--------+
```
---

I believe the queries mentioned above are semantically equivalent and thus their result should be the same.

Additionally, this result only occurs after the commit **99b9690**, before which both queries return the same result.

I encountered this issue when testing queries on the **FalkorDB master branch** in a Docker container running **redis:7.2.3-bookworm**.

### Steps to reproduce
Run the aforementioned, semantically equivalent, queries against an empty database and observe that their results differ.

### Expected behavior
The queries should result in the same behavior

### Actual behavior
The query results differ

**Comment by swilly22** [comment]
@CelineWuest thank you for bringing this up
The issue here is with eager operations such as `CREATE` these operation accumulate "records" passed to them from earlier operations within the execution and do not necessarily maintain the that order:

e.g.
```
GRAPH.QUERY g "UNWIND [0, 1] AS x RETURN x"
1) 1) "x"
2) 1) 1) (integer) 0
   2) 1) (integer) 1

----------------------------------------------------------------------------------------------------------------------------

GRAPH.QUERY g "UNWIND [0, 1] AS x CREATE () RETURN x"
1) 1) "x"
2) 1) 1) (integer) 1
   2) 1) (integer) 0
```

We'll try to maintain record incoming / outgoing order where possible.
